### ISSUE TITLE
How to migrate from TinyMCE 4 to TinyMCE 5

### ISSUE THREAD

**Issue by JellyBellyDev** [bramley/phplist-plugin-tinymce#5]
Hi, is possibile to have a new version of the plugin for TinyMCE 5?

Actually i have this notice:
![Schermata 2021-01-26 alle 12 42 00](https://user-images.githubusercontent.com/190820/105840904-0fefa080-5fd4-11eb-8cea-1bf05d1c9448.png)

to show this: https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/

Thanks!

**Comment by bramley** [comment]
I have had a quick look and the potential difficulty is to get the file manager, elFinder, to work.
Also, it appears that you will need to register with TinyMCE in order to use version 5. Is that your understanding?

**Comment by JellyBellyDev** [comment]
Yes, I know! Thanks for your time!

**Comment by JellyBellyDev** [comment]
I think that [this](https://github.com/nao-pon/tinymceElfinder) might help you! ;)

**Comment by bramley** [comment]
Thanks. I had already seen that and trying to incorporate it into the plugin.

As a workaround to the cloud version of TinyMCE 4 disappearing, you can install a version locally on your web server.

I have just installed 4.9.11 from https://www.tiny.cloud/get-tiny/self-hosted/ and it seems to be ok. It doesn't display the warning that the cloud version does.

Expand the zip file then copy the TinyMCE folder to your web site. Then update the "URL of tinymce.min.js" on the phplist Settings page.

I will try to get the plugin working with version 5. It is nearly there but one or two glitches.

**Comment by bramley** [comment]
I have updated the plugin to include a copy of TinyMCE 4 so that it will continue working after the cloud version disappears. You can update the plugin if you want to try that. But note that it will automatically use the local copy in preference to the cloud version.

**Comment by JellyBellyDev** [comment]
Hi @bramley your new [version](https://github.com/bramley/phplist-plugin-tinymce/releases/tag/2.2.0) works but show one error:
```
DevTools failed to load SourceMap: Could not load content for https://mydomain.com/admin/plugins/TinyMCEPlugin/tinymce/js/tinymce/skins/lightgray/skin.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

In Fact the content of the lightgray dir it's:
```
content.inline.min.css
content.min.css
content.mobile.min.css
fonts
img
skin.min.css
skin.mobile.min.css
```
Would it be possible to fix it?
Thank you

**Comment by bramley** [comment]
@JellyBellyDev Unless this is related to using TinyMCE 5 please create a new issue. Also explain what you are trying to do.

**Comment by JellyBellyDev** [comment]
Ok then I close. Thanks so much!
