### ISSUE TITLE
Error 500 when opening elFinder browser - IIS 6

### ISSUE THREAD

**Issue by babelouest** [bramley/phplist-plugin-tinymce#6]
Hello,

I'm using this plugin on a phplist installed on a Windows IIS server with php 5

Lately I installed the tinymce package onsite using #5 which works fine except for elFinder. When I click on the browser button, I have an error 500 but without any error message or description.
TheTinyMCEPlugin opens the following url: `/lists/admin/?pi=TinyMCEPlugin&page=connector_phplist&cmd=open&target=&init=1&tree=1&_=1634849628285` and this url result is an error 500 without body

The php error log show no message either.

I've upgraded elFinder with the latest version 2.1.59 which leads to the same error.

Any clue to help me?

**Comment by bramley** [comment]
In that issue I did explain that the plugin was not ready to use TinyMCE 5. I did some work on that earlier in the year but now don't remember quite what the problems were.

You should use the plugin from GitHub. You can also install a local copy of TinyMCE 4 if you want a later version than is in the plugin.

**Comment by babelouest** [comment]
Thanks, I'm working on an alternative then
